### ISSUE TITLE
Ошибка запуска бота: AttributeError: Can't pickle local object 'TelegramBaseClient.__init__.<locals>._Loggers'

### ISSUE THREAD

**Issue by alekla** [json1c/telegram-raid-botnet#21]
```
Traceback (most recent call last):
  File "/Users/NUCK/Downloads/BotnetTelegramBot-master/main.py", line 110, in <module>
    functions_storage.execute(choice)
  File "/Users/NUCK/Downloads/BotnetTelegramBot-master/modules/storages/functions_storage.py", line 65, in execute
    function = function_instance.execute()
  File "/Users/NUCK/Downloads/BotnetTelegramBot-master/functions/flood_chat.py", line 24, in execute
    flood.start_processes()
  File "/Users/NUCK/Downloads/BotnetTelegramBot-master/functions/flood.py", line 251, in start_processes
    process.start()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'TelegramBaseClient.__init__.<locals>._Loggers'
```

**Comment by alekla** [comment]
@json1c Привет
В чем может быть проблема?
Спасибо.
